### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [drNoob13/SimpleZshTheme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by drNoob13** [comment]
Thanks for your interest in this simple theme. A license has been added.

Cheers!

**Comment by unixorn** [comment]
Thanks, adding it.
